[path]

[path .class_feed]
extract_feed_Path = "libCore\\input\\rssFeed.json"

[path .api_local]
open_file = "local_api\\"

[path .log]
save_data_set = "dataset\\"
save_state = "saveState\\"
log_file = "log\\"

[path .prepare_data]
file_model = "libCore\\input\\languageModel.json"
file_stopword = "libCore\\input\\stopword.txt"

[path .read_data_dictionnary]
exclude_file = "dictionnary_neighbord\\exclude_file.txt"
dataset = "local_api\\"

[path .database]
database_run_sqlite = "database_rss_run\\database_don_t_touch\\db_Weak_Signal_Finder.db"
database_dictionnary_sqlite = "dictionnary_neighbord\\database\\dictionnaryWord.db"


[parameter]

[parameter .global_program]
argument_run = ["--silent_mode","--endpoint_user","--install","--engine_run"]

[parameter .endpoint_user]
initial_menu = {calcul = "calcul_parameter", request="request_parameter", help = "help_parameter", about = "about_parameter", exit = "exit_parameter"}
authorize_exit = "exit_parameter"
authorize_about = "about_parameter"
authorize_calcul = "calcul_parameter"
authorize_help = "help_parameter"
authorize_request = "request_parameter"
list_calcul = {concentration = "concentration_word_calcul"}
list_request = {find_by_pattern = "find_word_pattern"}
find_by_pattern_request = "find_word_pattern"
type_output_file = ["json","txt"]

[parameter .frequency_one_word]
filter_word = 1

[parameter .for_launch]
cooldown_day_launch_dictionnary = 1
cooldown_day_launch_inter_calcul_intensit_word = 7
part_of_local_api = "word_central_neighborhood"
authorize_run_intensity_engine = true
single_multiple_intensity_save = false # Enable 'true' if you have little memory resource available.

[parameter .email_auto]
authorize_run = true
server = "smtp.gmail.com"
port = 587
sender = "[EMAIL_ADDRESS]"
password_file = "password_app.env"
receiver = "[EMAIL_ADDRESS]"

[parameter .optimize]
batch_longer_list = 5000 #2,4,6,8,10,12,14,16,18,20... : number of divize for optimize the run.